{% set name = "straindesign" %}
{% set version = "3.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 91e9ab35e2b9aafdec687b76822f0ad4e4988c0b67924e5e7881ef78afedac72

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  build:
    - pip
    - python
    - pyyaml
    - setuptools
  run:
    - biopython
    - blessings
    - click
    - cobra >=0.24
    - escher
    - future
    - gnomic
    - inspyred
    - IProgress
    - lazy-object-proxy
    - plotly
    - python
    - markupsafe
    - networkx
    - numexpr
    - numpy <1.24 # Related to https://github.com/numpy/numpy/pull/22607
    - openbabel
    - openpyxl
    - optlang
    - ordered-set
    - palettable
    - pandas
    - redis-py
    - requests
    - scipy
    - seaborn

test:
  imports:
    - {{ name }}
  commands:
    - python -m {{ name }} --help

about:
  home: https://github.com/brsynth/{{ name }}
  summary: Library to perform metabolic engineering tasks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guillaume-gricourt
