{% set name = "CellProfiler" %}
{% set version = "4.2.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/CellProfiler/{{ name  }}/archive/v{{ version }}.tar.gz
  sha256: "cbade9a9330bd09024797139948f34ed4117c627e340742aca5cdf7267961576"

build:
  number: 0
  skip: True  # [py < 39]
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - python-javabridge
    - pytest
  run:
    - python
    - centrosome
    - docutils
    - cellprofiler-core {{ version }}
    - h5py  >=2.10
    - inflect
    - python-javabridge
    - joblib
    - mahotas
    - jinja2
    - sentry-sdk
    - matplotlib-base
    - mysqlclient
    - numpy  >=1.18.2,<=1.20.0
    - prokaryote
    - python-bioformats
    - requests
    - scikit-image  >=0.17.2
    - scikit-learn  >=0.20
    - scipy         >=1.4.1
    - six
    - wxpython
    - pillow

test:
  imports:
    - cellprofiler
  commands:
    - cellprofiler --help

about:
  home: https://github.com/CellProfiler/CellProfiler
  license: 3-clause BSD
  license_family: BSD
  license_file: LICENSE
  summary: "CellProfiler is free, open-source software for quantitative analysis of biological images"
  description: |
     CellProfiler is free, open-source software for quantitative analysis of biological images.No prior experience in programming or computer vision is required.

extra:
  container:
    extended-base: true
