
{% set version="2.3.2" %}

package:
  name: ensembl-xs
  version: {{ version }}

source:
  url: https://github.com/Ensembl/ensembl-xs/archive/refs/tags/{{ version }}.tar.gz
  sha256: aafc59568cd1042259196575e99cdfeef9c0fb7966e5f915cfaf38c70885ffa5

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - perl-app-cpanminus
  host:
    - perl

  run:
    - perl

test:
  imports:
    - Bio::EnsEMBL::XS

about:
  home: https://github.com/Ensembl/ensembl-xs
  license: Apache v2.0
  summary: A collection of XS modules to be used with the Ensembl APIs
