{% set version = "0.4.4" %}
{% set name = "gotree" %}

package:
  name: {{name}}
  version: {{ version }}

build:
  number: 0
  binary_relocation: false

source:
  - url: https://github.com/evolbioinfo/{{name}}/archive/v{{ version }}.tar.gz
    sha256: 7ca94f8d02dcfafabcb5fb228f382abae39f4c0eeca57e5a888b406ce7c48c7a
    folder: src/github.com/evolbioinfo/{{name}}/

requirements:
  build:
    - {{ go }}

test:
  commands:
    - {{name}} -h
    - {{name}}_test.sh
    - {{name}} version

about:
  home: https://github.com/evolbioinfo/{{name}}
  license: GPL-2.0
  summary: {{name}} is a set of command line tools to manipulate phylogenetic trees

extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
