{% set version = '0.8.2' %}

package:
  name: gappa
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/lczech/gappa/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e0e0de557ba26d1b5ff53535c8b7a8d763a5353771f49a2346ed50512f81250a

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - libgomp     # [linux]
    - cmake
  host:
    - zlib
    - openmp  # [osx]

test:
  commands:
    - gappa --help

about:
  home: https://github.com/lczech/gappa
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Genesis Applications for Phylogenetic Placement Analysis

extra:
  identifiers:
    - doi:10.1093/bioinformatics/bty767
