{% set version = '0.8.3' %}

package:
  name: gappa
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/lczech/gappa/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 736c2366df76d9637ef1b00dc82761e8594dd72c594773b4933475b57cb8a230

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - libgomp     # [linux]
    - cmake
  host:
    - zlib
    - openmp  # [osx]

test:
  commands:
    - gappa --help

about:
  home: https://github.com/lczech/gappa
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Genesis Applications for Phylogenetic Placement Analysis

extra:
  identifiers:
    - doi:10.1093/bioinformatics/bty767
