{% set version = "2.3.20230108193615" %}

package:
  name: cwltest
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cwltest/cwltest-{{ version }}.tar.gz
  sha256: ac8af0c3eb962d1df2c4d39b4e9e421a3b37c76e1e113ca1f7d9a52348de1686

build:
  number: 0
  noarch: python
  entry_points:
    - cwltest=cwltest:main
    - mock-cwl-runner=cwltest.tests.mock_cwl_runner:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv 

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - junit-xml >=1.8
    - python >=3.6
    - schema-salad >=5.0.20200220195218
    - defusedxml

test:
  imports:
    - cwltest
    - cwltest.tests
  commands:
    - cwltest --help
    - mock-cwl-runner --help

about:
  home: https://github.com/common-workflow-language/cwltest
  license: Apache-2.0
  summary: Common workflow language testing framework
