package:
  name: perl-file-chdir
  version: "0.1011"

source:
  url: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/File-chdir-0.1011.tar.gz
  sha256: 31ebf912df48d5d681def74b9880d78b1f3aca4351a0ed1fe3570b8e03af6c79

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-pathtools
    - perl-test-simple
    - perl-extutils-makemaker
    - perl-apache-test

  run:
    - perl
    - perl-pathtools

test:
  imports:
    - File::chdir

about:
  home: https://github.com/dagolden/File-chdir
  license: perl_5
  summary: 'a more sensible way to change directories'
