{% set name = "firecloud" %}
{% set version = "0.16.32.post1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e6443155c297f0db20441592f18e91d3d4c6c54eddf4bd47630d66c546b3537e

build:
  number: 0
  noarch: python
  entry_points:
    - fissfc = firecloud.fiss:main_as_cli
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - google-auth >=1.6.3
    - google-cloud-sdk
    - pydot
    - python
    - requests
    - six

test:
  imports:
    - firecloud
  commands:
    - fissfc --help

about:
  home: https://github.com/broadinstitute/fiss
  license: BSD-3-Clause
  license_family: BSD
  summary: API and CLI for Broad Institute's Firecloud workspace/workflow management service
  doc_url: https://software.broadinstitute.org/firecloud/
  dev_url: https://github.com/broadinstitute/fiss

extra:
  recipe-maintainers:
    - notestaff
