{% set name = "bifrost" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pmelsted/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 1db91bac58ebc1f5159f3b22f363821ac9113651cd9593f0cc6fa08ec7d3bf19

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - pthread-stubs
  run:
    - zlib
    - pthread-stubs

test:
  commands:
    - Bifrost --version

about:
   home: https://github.com/pmelsted/bifrost
   license: BSD-2-Clause
   license_family: BSD
   license_file: LICENSE
   summary: Highly parallel construction and indexing of colored and compacted de Bruijn graphs

extra:
   identifiers:
     - doi:10.1101/695338
