{% set version = "0.2" %}

package:
  name: nanospring
  version: {{ version }}

build:
  number: 0
  skip: True  # [osx]

source:
  url: https://github.com/qm2/NanoSpring/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5ad7fb4bd011b8092e7ca169cad7d7d37b5f32a568572955a484a07cbf8198b5

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake >=3.12
    - make
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - NanoSpring -h

about:
  home: https://github.com/qm2/NanoSpring
  license: MIT
  summary: NanoSpring is a compression tool for nanopore reads in Fastq files

