{% set name = "mashtree" %}
{% set version = "2.0" %}
{% set hash = "9c48493446541bf791ea19f19b0d4c6959f42a4d9b1281c58f78ca77b8bf2a89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lskatz/mashtree/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-module-build
    - perl-bioperl 
    - perl-dbd-sqlite >=1.58
  run:
    - perl
    - perl-bioperl >=1.7.2
    - perl-dbd-sqlite >=1.58
    - perl-file-which
    - mash  >=1.1
    - sqlite
    - quicktree
test:
  commands:
    - mashtree --version

about:
  home: https://github.com/lskatz/mashtree
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Create a tree using Mash distances'
