{% set version = "0.9.0" %}

package:
  name: pyfastx
  version: {{ version }}

source:
  url: https://github.com/lmdu/pyfastx/archive/{{ version }}.tar.gz
  sha256: e2e4a203cc0e23a5df32f6dcf8d5123f523375fea494586bf421905ee9ff9aef


build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [py2k]
  entry_points:
    - pyfastx = pyfastxcli:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - zlib
    - pip
  run:
    - zlib
    - python

test:
  imports:
    - pyfastx
  commands:
    - pyfastx --help

about:
  home: https://github.com/lmdu/pyfastx
  license: MIT
  license_file: LICENSE
  summary:  |
          pyfastx is a python module for fast random
          access to sequences from plain and gzipped
          FASTA/Q file
