{% set name = "chronumental" %}
{% set version = "0.0.55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chronumental-{{ version }}.tar.gz
  sha256: 1ac7622c60f6813ce65aad0e3d059f20ed920bc8724d4d5658d3734867075cdd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpyro ==0.9.0
    - pandas
    - python >=3.6
    - scipy
    - alive-progress
    - treeswift
    - xopen

test:
  imports:
    - chronumental
  commands:
    - chronumental -h
  requires:
    - pip

about:
  home: https://github.com/theosanderson/chronumental
  summary: Make time trees from large phylogenetic divergence trees
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tomkinsc
