{% set name = "pbbam" %}
{% set version = "2.3.0" %}
{% set sha256 = "89ce65643d636e443abc414e132c54f9de448841b54d3711463832458e2e73b2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PacificBiosciences/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage('pbbam', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - meson >=0.57.0
    - ninja
    - pkg-config
  host:
    - boost-cpp
    - zlib
    - htslib
    - pbcopper 2.0.0*
  run:
    - htslib
    - pbtk

about:
  home: https://github.com/PacificBiosciences/pbbam
  license: BSD-3-Clause-Clear
  summary: PacBio BAM C++ library

extra:
  recipe-maintainers:
    - pb-dseifert
    - mhsieh
    - pezmaster31
    - armintoepfer

test:
  commands:
    - test -f $PREFIX/lib/libpbbam*  # [unix]
