{% set version = "1.11" %}

package:
  name: tabix
  version: {{ version }}

build:
  noarch: generic
  number: 1
  run_exports:
    - {{ pin_subpackage('tabix', max_pin='x.x') }}

requirements:
  run:
    - htslib >=1.9

test:
  commands:
    - test -x "$PREFIX/bin/tabix"
    - test -x "$PREFIX/bin/bgzip"

about:
  home: https://github.com/samtools/htslib
  license: MIT
  summary: C library and command line tools for high-throughput sequencing data formats.

