{% set name = "kalign3" %}
{% set version = "3.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/TimoLassmann/kalign/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3067eb246b28e36508dc7cc9b418904ba8c6dbd2e894af6ff48e0e2a82b7abad

requirements:
  build:
  - {{ compiler('c') }}
  - make
  - automake
  - autoconf

test:
  commands:
    - kalign -v

about:
  home: https://github.com/TimoLassmann/kalign
  license: GPL3
  license_file: COPYING
  summary: 'Kalign is a fast and accurate multiple sequence alignment algorithm.'

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btz795
