{% set version = "1.3.9" %}

package:
  name: treeshrink
  version: {{ version }}

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/uym2/TreeShrink/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 460894699250b7fc1a7096d84bebb0b52b5551612e9faa283c600a15d3f756a3

requirements:
  host:
    - python >=3.6,<=3.9.15
    - setuptools
    - r-base

  run:
    - python >=3.6,<=3.9.15
    - r-base

test:
  imports:
    - treeshrink
  commands:
    - run_treeshrink -h

about:
  home: https://github.com/uym2/TreeShrink
  license_file: LICENSE
  license: GPL-3
  license_family: GPL
  summary: an algorithm for detecting abnormally long branches in one or more phylogenetic trees

extra:
  recipe-maintainer:
    - uym2 # (this recipe based on one available here: https://github.com//TreeShrink/tree/master/conda_package/treeshrink)