{% set name = "TEsorter" %}
{% set version = "1.4" %}
{% set sha256 = "9cf34229873af761ddec8c80a8082d3e22ef8a3b25a2a4b4db30c3373b840b4d" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/zhangrengang/TEsorter/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  entry_points:
    - TEsorter = TEsorter.app:main
  number: 0


requirements:
  host:
    - python >=3
    - pip
    - hmmer
  run:
    - python >=3
    - drmaa
    - pp
    - hmmer
    - blast
    - biopython

test:
  commands:
    - "TEsorter --version"
    - "TEsorter-test"

about:
  home: https://github.com/zhangrengang/TEsorter
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Lineage-level classification of transposable elements using conserved protein domains.
  dev_url: https://github.com/zhangrengang/TEsorter
