{% set name="recentrifuge" %}
{% set version="1.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

source:
  url: https://github.com/khyox/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 83ff179604affdc2c14b6ff50b9b8695237f8f9a1aea0b3a5e6897c758b22e0a

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - biopython >=1.78
    - numpy >=1.19.4
    - matplotlib-base >=3.3.3
    - openpyxl >=3.0.5
    - pandas >=1.1.5

test:
  commands:
    - rcf --version

about:
  home: https://github.com/khyox/recentrifuge
  license: 'GPLv3'
  license_file: LICENSE.txt
  summary: 'Robust comparative analysis and contamination removal for metagenomics'

extra:
  recipe-maintainers:
    - thanhleviet
  doi:
    - 10.1371/journal.pcbi.1006967
