{% set name = "svim" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/eldariont/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 63c31e6b22551641d02ac49371171b04d3ed0ab68650dca6fcb1e01da0b77347

requirements:
  host:
    - python >=3.6
    - pip
    - pysam >=0.15.2
    - numpy
    - scipy
    - matplotlib-base >=3.3.0
    - edlib
    - pyspoa >=0.0.6
    - py-cpuinfo >=7.0.0
  run:
    - python >=3.6
    - pysam >=0.15.2
    - numpy
    - scipy
    - matplotlib-base >=3.3.0
    - edlib
    - pyspoa >=0.0.6
    - py-cpuinfo >=7.0.0
    - ngmlr
    - minimap2
    - samtools

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

test:
  imports:
    - svim
    - tests
  commands:
    - svim -h

about:
  home: 'https://github.com/eldariont/svim'
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: SVIM is a structural variant caller for long reads.

extra:
  recipe-maintainers:
    - eldariont
