{% set name = "duplex-tools" %}
{% set version = "0.2.19" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/d/duplex_tools/duplex_tools-{{ version }}.tar.gz"
  sha256: 62ea76f319b8494fa50094e599a4cb54a88e070db46aacb3e7abd17986b19455

build:
  number: 0
  entry_points:
    - duplex_tools = duplex_tools:main
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python
  
requirements:
  host:
    - pip
    - python
  run:
    - python-edlib
    - more-itertools
    - natsort
    - numpy
    - pandas
    - parasail-python
    - pathlib
    - pyfastx
    - pysam
    - python
    - tqdm

test:
  imports:
    - duplex_tools
  commands:
    - duplex_tools --help

about:
  home: "https://github.com/nanoporetech/duplex-tools"
  license: MPL-2.0
  license_file: LICENSE.md
  summary: "Duplex Tools contains a set of utilities for dealing with ONT Duplex sequencing data"

extra:
  recipe-maintainers:
    - ollenordesjo
