{% set version = "1.3.2" %}
{% set sha256 = "fc8d4ac3cd0ee838fe72db8d6afd1bbace1c2ac2d98d03341232a8bbd33f4f43" %}

package:
  name: ivar
  version: {{ version }}

source:
  url: "https://github.com/andersen-lab/ivar/archive/v{{ version }}.tar.gz"
  sha256: "{{ sha256 }}"

build:
  number: 0

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - make
    - automake
    - autoconf
    - libtool
    - pkg-config
  host:
    - htslib
  run:
    - htslib
    - samtools

test:
  commands:
    - ivar version

about:
  home: https://andersen-lab.github.io/ivar/html/
  license: GPL-3.0
  license_file: LICENSE
  summary: iVar is a computational package that contains functions broadly useful for viral amplicon-based sequencing.
  dev_url: https://github.com/andersen-lab/ivar

extra:
  identifiers:
    - biotools:ivar
    - usegalaxy-eu:ivar_variants
