{% set version = "2.5.1" %}

package:
  name: bowtie2
  version: {{ version }}

source:
  url: https://github.com/BenLangmead/bowtie2/archive/v{{ version }}.tar.gz
  sha256: 605acac750436b40762e113d3fc755013efcfaec962aa71df45e362d5444f263

build:
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - zlib
    - zstd
    - tbb-devel
    - tbb
  run:
    - python
    - perl
    - zlib
    - zstd
    - tbb

test:
  commands:
    - bowtie2 --help
    - bowtie2 --version
    # test if bowtie2 reports its version
    - bowtie2 --version | grep -q "bowtie2-align-s version [0-9]"  # [linux]
    - bowtie2-align-l --help
    - bowtie2-align-s --help
    - bowtie2-build --help
    - bowtie2-build-l --help
    - bowtie2-build-s --help
    - bowtie2-inspect --help
    - bowtie2-inspect-l --help
    - bowtie2-inspect-s --help

about:
  home: 'http://bowtie-bio.sourceforge.net/bowtie2/index.shtml'
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and sensitive gapped read alignment

extra:
  identifiers:
    - biotools:bowtie2
    - doi:10.1038/nmeth.1923
    - debian:bowtie2
    - usegalaxy-eu:bowtie2
