{% set name = "perl-uri" %}
{% set version = "5.17" %}
{% set sha256 = "5f7e42b769cb27499113cfae4b786c37d49e7c7d32dbb469602cd808308568f8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/URI-5.17.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-encode
    - perl-exporter
    - perl-carp
    - perl-test
    - perl-mime-base64
    - perl-test-needs
    - perl-data-dumper
    - perl-file-temp
    - perl-constant
    - perl-parent
    - perl-extutils-makemaker
    - perl-business-isbn

  run:
    - perl
    - perl-encode
    - perl-exporter
    - perl-carp
    - perl-mime-base64
    - perl-data-dumper
    - perl-constant
    - perl-parent
    - perl-business-isbn

test:
  imports:
    - URI

about:
  home: https://github.com/libwww-perl/URI
  license: perl_5
  summary: 'Uniform Resource Identifiers (absolute and relative)'
