{% set name = "perl-uri" %}
{% set version = "5.15" %}
{% set sha256 = "af31b673d91b1b96ea2842523ee03f54039f2ae6a5f40d9cdadf73221f8a586c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/URI-5.15.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-encode
    - perl-exporter
    - perl-carp
    - perl-test
    - perl-mime-base64
    - perl-test-needs
    - perl-data-dumper
    - perl-file-temp
    - perl-constant
    - perl-parent
    - perl-extutils-makemaker
    - perl-business-isbn

  run:
    - perl
    - perl-encode
    - perl-exporter
    - perl-carp
    - perl-mime-base64
    - perl-data-dumper
    - perl-constant
    - perl-parent
    - perl-business-isbn

test:
  imports:
    - URI

about:
  home: https://github.com/libwww-perl/URI
  license: perl_5
  summary: 'Uniform Resource Identifiers (absolute and relative)'
