{% set version = "0.4" %}

package:
  name: asqcan
  version: {{ version }}

source:
  url: https://github.com/bogemad/asqcan/archive/v{{ version }}.tar.gz
  sha256: 39fef93c8e0d1e2c30e8f143906855f4319c3f5bc9e67711fc6a9303f375a947

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - bwa
    - samtools
    - diamond
    - parallel
    - fastp
    - spades
    - quast
    - blobtools
    - blast
    - prokka

test:
  commands:
    - asqcan -h

about:
  home: https://github.com/bogemad/asqcan
  license: GPL-3.0-only
  summary: 'A combined pipeline for bacterial genome assembly, quality control and annotation'
  license_family: GPL
