{% set version = "0.3.15" %}

package:
  name: hap.py
  version: '{{ version }}'

source:
  url: https://github.com/Illumina/hap.py/archive/v{{ version }}.tar.gz
  sha256: 79f76292c03ff454277f7c4d20eb863e78ba266ebf20e91bff96ff0c87269ebd

build:
  number: 0
  skip: true # [not py27 or osx]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - autoconf
    - automake
  host:
    - python
    - setuptools
    - cython
    - numpy
    - pandas
    - pybedtools
    - pysam
    - nose
    - bx-python
    - boost-cpp
    - htslib
    - bcftools
    - samtools
  run:
    - python
    - numpy
    - pandas
    - pybedtools
    - pysam
    - scipy
    - nose
    - bx-python
    - bcftools
    - samtools


test:
  commands:
    - hap.py -h
    - som.py -h

about:
  home: https://github.com/Illumina/hap.py
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Haplotype VCF comparison tools
