{% set version = "1.0.7" %}

package:
  name: zdb
  version: {{ version }}


build:
  number: 0
  noarch: generic


source:
  url: https://github.com/metagenlab/zDB/archive/refs/tags/v1.0.7.tar.gz
  sha256: c3eb7940144c95728acdb7d004872c3f906f9f7c49cc24f6a1fd0c15ba95eb40 


requirements:
  run:
    - nextflow >=21.04.0

test:
  commands:
    - "zdb"

about:
  home: https://github.com/metagenlab/zDB/
  license: MIT
  license_file: LICENSE
  summary: zDB is both a bacterial comparative genomics pipeline and a tool to visualize the results
  dev_url: https://github.com/metagenlab/zDB/

extra:
  recipe-maintainers:
    - bkm
  identifiers:
    - biotools:zDB
