{% set version = "0.18.2" %}
{% set sha256 = "142f1178d9caa7bdd8b2dba1ee98c1df2792cafe494a43fbd59e00a95e9ef64b" %}



package:
  name: dr-disco
  version: '{{version}}'

source:
  url: https://github.com/yhoogstrate/dr-disco/archive/v{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python <3
    - pip
    - numpy
    - scipy
  run:
    - python <3
    - scipy
    - pysam
    - click
    - fuma
    - HTSeq
    - pyfaidx
    - tqdm

test:
  imports:
    - drdisco

  commands:
    # click requires a unicode locale
    - LANG=C.UTF-8 dr-disco --version

about:
  home: https://github.com/yhoogstrate/dr-disco
  license: GPL-3.0+
  license_file: LICENSE
  license_family: GPL
  summary: 'Dr. Disco: fusion gene and genomic breakpoint detection in random hexamer
    RNA-seq data'
