{% set version = "0.3" %}

package:
  name: miniasm
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/lh3/miniasm/archive/refs/tags/v0.3.tar.gz
  sha256: 8ff47f869afbf20845481d8a8f21afa4ba9abe36847666e88b23351bb9192af7

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - miniasm -V

about:
  home: https://github.com/lh3/miniasm
  license: MIT
  license_file: LICENSE.txt
  summary: Ultrafast de novo assembly for long noisy reads (though having no consensus step)
