{% set version = "1.3.2" %}
{% set sha256 = "46e0d102467276d0aee5c493e5e678c76120760f0dbe57caf4d880d366dcb285" %}

package:
  name: hapog
  version: '{{version}}'

source:
  url: https://github.com/institut-de-genomique/HAPO-G/archive/refs/tags/{{version}}.tar.gz
  sha256: '{{sha256}}'
  patches:
    - fix_cmake.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - 'python>=3.7'
    - biopython
    - htslib
    - setuptools
  run:
    - htslib
    - 'python>=3.7'
    - biopython
    - bwa
    - samtools
    - minimap2

test:
  commands:
    - hapog -h
    - hapog.py -h

about:
  home: https://github.com/institut-de-genomique/HAPO-G
  license: OTHER
  license_file: LICENSE.md
  summary: Haplotype-Aware Polishing of Genomes

extra:
  identifiers:
    - doi:10.1093/nargab/lqab034
