{% set version = "1.3.1" %}
{% set sha256 = "cfc9d557e716da68ce0810c76794cde32b614d915e9009ffb704aea2d22a98b5" %}

package:
  name: hapog
  version: '{{version}}'

source:
  url: https://github.com/institut-de-genomique/HAPO-G/archive/refs/tags/{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - 'python>=3.6'
    - htslib
  run:
    - htslib
    - 'python>=3.6'
    - biopython
    - bwa
    - samtools
    - minimap2

test:
  commands:
    - hapog.py -h

about:
  home: https://github.com/institut-de-genomique/HAPO-G
  license: OTHER
  license_file: LICENSE.md
  summary: Haplotype-Aware Polishing of Genomes

extra:
  identifiers:
    - doi:10.1093/nargab/lqab034
