{% set version = "2" %}

package:
  name: xs-sim
  version: {{ version }}

source:
  url: https://github.com/pratas/xs/archive/refs/tags/v2.tar.gz
  sha256: 05f4aef0235166353d63074f7f78e148915d4b896f209a4510fc51ddc3011fe4

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}

test:
  commands:
    - XS -n 1 /dev/null
    
about:
  home: https://github.com/pratas/xs
  license: GPL-2.0
  license_file: LICENSE
  summary: Simulates NGS reads
  description: |
    XS is a skilled FASTQ read simulation tool, flexible, portable
    (does not need a reference sequence) and tunable in terms of
    sequence complexity
    
extra:
  recipe-maintainers:
    - TMiguelT
