{% set version = "0.6.3" %}

package:
  name: scnic
  version: {{ version }}

source:
  url: https://github.com/lozuponelab/SCNIC/archive/{{ version }}.tar.gz
  sha256: a942dbdbe43ef15767bc22ee4aea7c005af333570aa6ddda356c6b7ca657de3e

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3
    - setuptools
    - pytest-runner
  run:
    - python >=3
    - numpy
    - scipy
    - pandas
    - statsmodels
    - h5py
    - biom-format
    - networkx >2
    - scikit-bio
    - fastspar
    - tqdm
    - matplotlib-base
    - seaborn

test:
  command:
    - SCNIC_analysis.py --help
    - fastspar --help  # verify fastspar working correctly

about:
  home: https://github.com/lozuponelab/SCNIC
  license: BSD
  license_file: LICENSE
  summary: "SCNIC: Sparse Cooccurence Network Investigation for Compositional data"

extra:
  recipe-maintainers:
    - lozuponelab
