{% set version = "0.30.18" %}
{% set sha256hash = "9066d2ad1cec0a7dae7326c7591c8b51b5129f2df23798e0da8a55ac2e9384f5" %}

package:
  name: cyvcf2
  version: {{ version }}

source:
  url: https://github.com/brentp/cyvcf2/archive/v{{ version }}.tar.gz
  sha256: {{ sha256hash }}
#  patches:
#    # Link to htslib shipped by conda
#    - patches/setup.py.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - zlib
    - libcurl
    # statically links to htslib, sadly
    - htslib
    - openssl
    - bzip2
    - xz
  run:
    - python
    - numpy
    - zlib
    - coloredlogs
    - click
    - libcurl
    - openssl
    - pathlib2  # [py<34]
    - bzip2
    - xz

test:
  imports:
    - cyvcf2

about:
  home: https://github.com/brentp/cyvcf2
  summary: A cython wrapper around htslib built for fast parsing of Variant Call Format (VCF) files
  license: MIT
