{% set name = "ribotish" %}
{% set version = "0.2.7" %}
{% set sha256 = "edb574a3a35f5d63809f79e383d3786bcf0b72a118ff788c93c1dda4f0cc8f99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zhpn1024/ribotish/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python -m pip install --no-deps --ignore-installed .
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pysam
    - matplotlib-base

test:
  commands:
    - ribotish -h

about:
  home: https://github.com/zhpn1024/ribotish
  license: GPL-3
  license_file: LICENSE
  summary: Ribo TIS Hunter (Ribo-TISH) identifies translation activities using ribosome profiling data.
