{% set version="2.0.3.0" %}
{% set hash="hashhash" %}

package:
  name: checkm-genome
  version: {{ version }}

source:
  url: https://github.com/chklovski/CheckM2/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python>=3.6
    - scikit-learn=0.23.2
    - h5py=2.10.0
    - numpy>=1.16.4
    - diamond>=2.0.4
    - tensorflow >= 2.3.0
    - lightgbm >= 3.2.1
    - pandas >=1.3
    - scipy
    - prodigal>=2.6.3
    - setuptools
    - requests
    - packaging
    - tqdm

test:
  commands:
    checkm2 -h

about:
  recipe-maintainers:
    - chklovski
  home: https://github.com/chklovski/CheckM2
  license: GPL3
  license_file: LICENSE
  summary: 'Rapid assessment of genome bin quality using machine learning.'
