{% set version = "0.3.6" %}
{% set name = "goalign" %}

package:
  name: {{name}}
  version: {{ version }}

build:
  number: 0
  binary_relocation: false

source:
  - url: https://github.com/evolbioinfo/{{name}}/archive/v{{ version }}.tar.gz
    sha256: fd2d7547d1159d06b11c35332da4a38204dc2beb3b1d7a0299d37bf757ad7d2f
    folder: src/github.com/evolbioinfo/{{name}}/

requirements:
  build:
    - {{ go }}

test:
  commands:
    - {{name}} -h
    - goalign_test.sh
    - {{name}} version

about:
  home: https://github.com/evolbioinfo/goalign
  license: GPL-2.0
  summary: goalign is a set of command line tools to manipulate multiple alignments

extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
