{% set name = "gtfparse" %}
{% set version = "1.3.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d957f18e5f70413f89a28ef83068c461b6407eb38fd30e99b8da3d69143527b1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - numpy >=1.7,<2.0
    - pandas >=0.15

  run:
    - python
    - numpy >=1.7,<2.0
    - pandas >=0.15

test:
  imports:
    - gtfparse

about:
  home: https://github.com/openvax/gtfparse
  license: Apache 2.0
  summary: 'GTF Parsing'
  license_family: APACHE
