{% set name = "gtfparse" %}
{% set version = "2.0.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "c45439af58cb48120910bebe4625371d8fb5735f12a749e8933c9d6f2b1a558c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - numpy >=1.7,<2.0
    - pandas >=0.15

  run:
    - python
    - numpy >=1.7,<2.0
    - pandas >=0.15

test:
  imports:
    - gtfparse

about:
  home: https://github.com/openvax/gtfparse
  license: Apache 2.0
  summary: 'GTF Parsing'
  license_family: APACHE
