{% set name = "segzoo" %}
{% set version = "1.0.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2f516cba94845cce3025d0fcb85b9c8bdb12306d58617491a36316bff0c85260

build:
  noarch: python
  number: 0
  entry_points:
    - segzoo=segzoo.main:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
   - python ==3.8.*
   - pip
  run:
    - python ==3.8.*
    - seaborn
    - segtools
    - ggd
    - snakemake
    - pybedtools
test:
  imports:
    - segzoo
  commands:
    - segzoo --help

about:
  home: "https://github.com/hoffmangroup/segzoo"
  license: "GNU General Public v2 (GPLv2)"
  license_family: GPL2
  license_file: LICENSE.txt
  summary: "System for turnkey analysis of semi-automated genome annotations"

extra:
  recipe-maintainers:
    - mmendez12
