package:
  name: multiz
  version: "20190527"

build:
  number: 0

source:
  url: https://github.com/multiz/multiz/archive/refs/tags/20190527.tar.gz
  sha256: e683230f3b7c3253f3ab91c110944d21f46274a71d0894e347330259313619c9

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
  run:

test:
  commands:
    - multiz 2>&1 | grep -qF 'multiz.v11.2'
    - tba 2>&1 | grep -qF 'tba.v12'
    - roast 2>&1 | grep -qF 'roast.v3'

about:
  home: http://www.bx.psu.edu/miller_lab/
  license: MIT
  summary: DNA multiple sequence aligner from Penn State's Miller lab.

extra:
  identifiers:
    - biotools:multiz
    - biotools:tba
    - biotools:roast
