{% set name = "jcvi" %}
{% set version = "1.2.11" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 627f2683030c74bf81a84c74c29cee5e348e3b2b8f85df873dc36c6c405dff33

build:
  skip: True  # [py2k]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy 
    - cython
  run:
    - python
    - biopython
    - boto3
    - brewer2mpl
    - coveralls
    - deap
    - ete3
    - gffutils
    - goatools
    - graphviz
    - jinja2
    - matplotlib-base
    - natsort
    - networkx
    - numpy
    - pypdf2
    - pytest
    - pytest-benchmark
    - pytest-cov
    - pyyaml
    - rich
    - scipy
    - seaborn
    #- texlive-core
    - ucsc-liftover

test:
  imports:
    - jcvi
    - jcvi.algorithms
    - jcvi.annotation
    - jcvi.apps
    - jcvi.assembly
    - jcvi.compara
    - jcvi.formats
    - jcvi.graphics
    - jcvi.projects
    - jcvi.utils
    - jcvi.utils.data
    - jcvi.variation
  #This fails for some unknown reason, even though it's outputting "JCVI utility libraries"
  #commands:
  #  - "python -m jcvi.apps 2>&1 | grep 'JCVI utility libraries'"

about:
  home: http://github.com/tanghaibao/jcvi
  license: BSD-2-Clause
  license_family: BSD
  summary: Python utility libraries on genome assembly, annotation and comparative genomics
  description: "JCVI utility libraries"
