{% set name = "igv" %}
{% set version = "2.15.4" %}
{% set sha256 = "baa1584ac96cd7ac2fb03dabf23dd837538a82e8f8b54aed012e74e90c8f5320" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/igvteam/igv/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk >=11
  run:
    - openjdk >=11

test:
  commands:
    - igv --version
    - igv_hidpi --version

about:
  home: http://www.broadinstitute.org/software/igv/home
  license: MIT
  summary: |
    Integrative Genomics Viewer. Fast, efficient, scalable visualization tool for genomics
    data and annotations.

extra:
  identifiers:
    - biotools:igv
