{% set name = "igv" %}
{% set version = "2.15.5" %}
{% set sha256 = "f17bee71d3b342d14da76a758e4f0a99b3be0eaa2b7c724aeb83e7a0805a716e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/igvteam/igv/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk >=11
  run:
    - openjdk >=11

test:
  commands:
    - igv --version
    - igv_hidpi --version

about:
  home: http://www.broadinstitute.org/software/igv/home
  license: MIT
  summary: |
    Integrative Genomics Viewer. Fast, efficient, scalable visualization tool for genomics
    data and annotations.

extra:
  identifiers:
    - biotools:igv
