name: Bulk branch
on:
  push:
    branches:
      - bulk
      - osx-debug
jobs:
  build-linux:
    if: ${{ false }}
    name: Bulk Linux Builds
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 13
      matrix:
        runner: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] #, 13, 14, 15, 16, 17, 18, 19]
    steps:
    - uses: actions/checkout@v1

    - name: Fetch common.sh
      run: |
        wget https://raw.githubusercontent.com/bioconda/bioconda-common/bulk/common.sh

    - name: Restore cache
      id: cache
      uses: actions/cache@v1
      with:
        path: /home/runner/bioconda
        key: ${{ runner.os }}--bulk--${{ hashFiles('**/common.sh') }}

    - name: Setup Bioconda-utils
      if: steps.cache.outputs.cache-hit != 'true'
      uses: bioconda/bioconda-actions/bioconda_recipes_setup/@bulk
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Build and upload
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        INVOLUCRO_AUTH: ${{ secrets.INVOLUCRO_AUTH }}
        QUAY_OAUTH_TOKEN: ${{ secrets.QUAY_OAUTH_TOKEN }}
        # Mimic circleci
        OSTYPE: "linux-gnu"
        CI: "true"
      run: |
        ls /home/runner/bioconda/etc/profile.d
        ls /home/runner/bioconda/etc
        . /home/runner/bioconda/etc/profile.d/conda.sh
        conda activate base
        echo '============'
        conda info --all
        conda config --show-sources
        python -c 'import bioconda_utils.utils as u ; import pathlib as p ; print(*(f"{f}:\n{p.Path(f).read_text()}" for f in u.load_conda_build_config().exclusive_config_files), sep="\n")'
        echo '============'
        bioconda-utils build recipes config.yml \
          --worker-offset ${{ matrix.runner }} --n-workers 13 \
          --docker --mulled-test --anaconda-upload --mulled-upload-target biocontainers
        conda clean -y --all

  build-osx:
    name: Bulk OSX Builds
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        runner: [0]
    steps:
    - uses: actions/checkout@v1

    - name: Fetch common.sh
      run: |
        wget https://raw.githubusercontent.com/bioconda/bioconda-common/bulk/common.sh

    - name: Restore cache
      id: cache
      uses: actions/cache@v1
      with:
        path: /Users/runner/miniconda
        key: ${{ runner.os }}--bulk-macos-${{ hashFiles('**/common.sh') }}

    - name: OSX stuff
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        # Remove existing installation on macOS runners
        sudo rm -rf /usr/local/miniconda
        sudo rm -rf ${HOME}/miniconda

        # Extract the versions we should be using from the previously-downloaded common.sh
        BIOCONDA_UTILS_TAG=$(grep "^BIOCONDA_UTILS_TAG=" common.sh | cut -f2 -d "=" | sed "s/^v//g")
        MINICONDA_VER=$(grep "^MINICONDA_VER=" common.sh | cut -f2 -d "=")

        # Basic miniconda installation with bioconda channels configured
        curl "https://repo.anaconda.com/miniconda/Miniconda3-${MINICONDA_VER}-MacOSX-x86_64.sh" > miniconda.sh
        bash miniconda.sh -b -p "${HOME}/miniconda"
        export PATH="${HOME}/miniconda/bin:${PATH}"
        conda config --set always_yes yes
        conda config --system --add channels defaults
        conda config --system --add channels bioconda
        conda config --system --add channels conda-forge
        conda config --system --set channel_priority strict
        conda info

        # The run_conda_forge_build_setup script, from the conda-forge-ci-setup
        # script, helps install required SDK for macOS.
        #
        # Installing bioconda-utils and conda-forge-ci-setup with conda causes dependency conflicts.
        # Installing bioconda-utils and conda-forge-ci-setup with mamba works fine.
        conda install -y mamba
        mamba install bioconda-utils=${BIOCONDA_UTILS_TAG} conda-forge-ci-setup
        ${HOME}/miniconda/bin/run_conda_forge_build_setup

        # Set local channel as highest priority
        mkdir -p "${HOME}/miniconda/conda-bld/{noarch,linux-64,osx-64}"
        conda index "${HOME}/miniconda/conda-bld"
        conda config --system --add channels "file://${HOME}/miniconda/conda-bld"

        echo "MACOSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET}"
        echo "xcode-select -p=$(xcode-select -p)" # /Applications/Xcode_13.2.1.app/Contents/Developer
        echo "OSX_SDK_DIR=${OSX_SDK_DIR}"  # $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs
        echo "CONDA_BUILD_SYSROOT=${CONDA_BUILD_SYSROOT}"

        # Based on conda-forge-ci-setup, expecting maybe
        # /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
        #
        # However locally for xcode-select -p I get:
        # /Library/Developer/CommandLineTools

        echo "SYSROOT=${SYSROOT}"          # 
        ls $(xcode-select -p)
        ls $(xcode-select -p)/Platforms
        ls $(xcode-select -p)/Platforms/MacOSX.platform
        ls $(xcode-select -p)/Platforms/MacOSX.platform/Developer
        ls $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs

        exit 1


    - name: Build and upload
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        INVOLUCRO_AUTH: ${{ secrets.INVOLUCRO_AUTH }}
        QUAY_OAUTH_TOKEN: ${{ secrets.QUAY_OAUTH_TOKEN }}
        # Mimic circleci
        OSTYPE: "darwin"
        CI: "true"
      run: |
        export PATH="${HOME}/miniconda/bin:${PATH}"
        echo '============'
        conda info --all
        conda config --show-sources
        python -c 'import bioconda_utils.utils as u ; import pathlib as p ; print(*(f"{f}:\n{p.Path(f).read_text()}" for f in u.load_conda_build_config().exclusive_config_files), sep="\n")'
        echo '============'
        bioconda-utils build recipes config.yml \
          --worker-offset ${{ matrix.runner }} --n-workers 1 \
          --packages python-hyphy-python
        conda clean -y --all
